### ISSUE TITLE
Bug: "Backup images before processing" checkbox is unselectable on application built from latest as of 27th of June

### ISSUE THREAD

**Issue by O-J1** [LeonardoFer/DatasetHelpers#1] opened 2023-06-27 06:44 UTC
**Expected:** Clicking on "Backup images before processing" checkbox works and a tick is displayed

**Observed:** Clicking no matter what does not make any visual change. The checkbox is selectable **before** setting an input folder

![image](https://github.com/LeonardoFer/DatasetHelpers/assets/18110006/6e55752d-a83b-41e3-a37e-7488f9ae818a)

**Steps to reproduce:**

1. git clone repo
2. install `windowsdesktop-runtime-7.0.8-win-x64.exe`
3. Update VS to latest
4. Install dependencies detected by VS
5. Build project
6. Run
7. Click on Sort
8. Set input location
9. Tick the checkbox

**System Info:**
```
OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	FW-OJ
System Manufacturer	Framework
System Model	Laptop (12th Gen Intel Core)
System Type	x64-based PC
System SKU	FRANDACP06
Processor	12th Gen Intel(R) Core(TM) i7-1260P, 2100 Mhz, 12 Core(s), 16 Logical Processor(s)
BIOS Version/Date	INSYDE Corp. 03.06, 10/11/2022
SMBIOS Version	3.3
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Framework
BaseBoard Product	FRANMACP06
BaseBoard Version	A6
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.1413"
Username	FW-OJ\redacted
Time Zone	AUS Eastern Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.7 GB
Available Physical Memory	21.8 GB
Total Virtual Memory	33.7 GB
Available Virtual Memory	22.9 GB
Page File Space	2.00 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualisation-based security	Running
Virtualisation-based security required security properties	
Virtualisation-based security available security properties	Base Virtualisation Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualisation
Virtualisation-based security services configured	Hypervisor enforced Code Integrity
Virtualisation-based security services running	Credential Guard, Hypervisor enforced Code Integrity, Hardware-enforced Stack Protection (Kernel-mode)
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

```

**Comment by LeonardoFer** [comment] 2023-06-27 09:41
I've been trying to reproduce it but no luck so far.
I've observed before that sometimes there's a delay in the GUI even though it shouldn't have.
For example: I tried to reproduce the steps for this and indeed it doesn't mark the checkbox after selecting the input folder but if you wait a few seconds it will work. 
I honestly don't know what is the cause for this delay, if its my code, MAUI or something else.

Could you try to see if you can mark the checkbox a few seconds after selecting the input folder?

**Comment by LeonardoFer** [comment] 2023-06-28 10:40
I will close the issue since we discussed it already in discord.

**Closed by LeonardoFer** 2023-06-28 10:40 UTC
